#!/usr/bin/env bash
echo "Informações do Sistema"

echo -n "Usuário: "
whoami

echo -n "Hostname: "
hostname

echo -n "Uptime: "
uptime -p

echo -n "Kernel: "
uname -rms
[ -x ap1 ]; echo $?

read name
echo $name
